# Generated by Django 6.1 on 2026-09-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0003_turf_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='sport_type',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('multi', 'Multi-sport')], default='multi', max_length=20),
        ),
    ]
