# Generated by Django 6.1 on 2026-09-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0004_turf_description_turf_sport_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('turf', 'date', 'start_time', 'end_time'), name='unique_turf_slot'),
        ),
    ]
