# Generated by Django 6.1 on 2026-09-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0005_slot_unique_turf_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='turfs/'),
        ),
    ]
