# Generated by Django 6.1 on 2026-09-13 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0006_turf_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='amenities',
            field=models.TextField(blank=True, help_text='Example: Floodlights, Parking, Changing Room, Drinking Water'),
        ),
        migrations.AddField(
            model_name='turf',
            name='full_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turf',
            name='map_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='turf',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='turf',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='turf',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='sport_type',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('pickleball', 'Pickleball'), ('multi', 'Multi-sport')], default='multi', max_length=20),
        ),
        migrations.CreateModel(
            name='TurfImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='turfs/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='turfs.turf')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
