# Generated by Django 6.1 on 2026-09-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0007_turf_amenities_turf_full_address_turf_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='price_per_hour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
