# Generated by Django 6.1 on 2026-09-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0008_alter_turf_price_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='turf',
            name='sport_type',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('pickleball', 'Pickleball'), ('multi', 'Multi-sport')], default='multi', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='turf',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='turfs', to='turfs.sport'),
        ),
    ]
